INSERT  INTO DEPARTMENT (ID, NAME, LOCATION) VALUES (1, 'HR', 'NewYork');
INSERT  INTO DEPARTMENT (ID, NAME, LOCATION) VALUES (2, 'IT', 'Boston');
INSERT  INTO DEPARTMENT (ID, NAME, LOCATION) VALUES (3, 'Finance', 'Bentonville');
INSERT  INTO DEPARTMENT (ID, NAME, LOCATION) VALUES (4, 'Admin', 'Hartford');
INSERT  INTO DEPARTMENT (ID, NAME, LOCATION) VALUES (5, 'Sales', 'NewJersey');